import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Wrapper from "./components/Wrapper";
import SideNav from "./components/SideNav";
import Footer from "./components/Footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-black">
          <Wrapper>
            <div className="flex ">
              <SideNav />
              <div className=" w-full">
                <Navbar />
                <div className="container m-auto min-h-[650px]">
                  {children}
                </div>
              </div>
            </div>
            <Footer />
          </Wrapper>
        </div>
      </body>
    </html>
  );
}
